ontology_name: "Domain Electrochemistry"
ontology_adjective: "electrochemical"
ontology_noun: "electrochemistry"
ontology_abbreviation: "ECHO"
ontology_uri: "https://w3id.org/emmo/domain/electrochemistry"
ontology_prefix: "https://w3id.org/emmo/domain/electrochemistry#"
ontology_description: "The ontology for electrochemical systems."

ttl_files:
  - section_title: "Electrochemistry Domain Ontology (ECHO)"
    path: "electrochemistry.ttl"
  - section_title: "Electrochemistry Reference"
    path: "reference/electrochemistry-reference.ttl"
  - section_title: "Electrochemistry Quantities"
    path: "reference/electrochemistry-quantities.ttl"
  - section_title: "Electrochemistry Manufacturing"
    path: "modules/electrochemistry-manufacturing.ttl"
  - section_title: "Electrochemistry Testing"
    path: "modules/electrochemistry-testing.ttl"

output:
  inferred_ttl: "electrochemistry-inferred.ttl"
  rst_file: "docs/electrochemistry.rst"

emmocheck_classes:
  - "electrochemistry.ElectrochemicalQuantity"
  - "electrochemistry.ElectrochemicalKineticQuantity"
  - "electrochemistry.ElectrochemicalTransportQuantity"
  - "electrochemistry.ElectrochemicalThermodynamicQuantity"
  - "electrochemistry.ElectrochemicalConstant"
  - "electrochemistry.ReactionRateConstant"
  - "electrochemistry.PercentUnit"
