# Configurations used when running emmocheck from the ci_tests workflow
skip:
  - test_namespace
  - test_dimensional_unit

test_quantity_dimension:
  exceptions:
    - electrochemistry.ElectrochemicalQuantity
    - electrochemistry.ElectrochemicalKineticQuantity
    - electrochemistry.ElectrochemicalTransportQuantity
    - electrochemistry.ElectrochemicalThermodynamicQuantity
    - electrochemistry.ElectrochemicalConstant
    - BattINFO.BatteryQuantity
    # We ignore reaction rate constant since its dimensionality may vary
    - electrochemistry.ReactionRateConstant

test_dimensional_unit:
  exceptions:
    - electrochemistry.PercentUnit
    - electrochemistry.CRateUnit
