name: EMMO check

on: [pull_request]

jobs:
  emmocheck:
    name: EMMO Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install EMMOntoPy
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt

    - name: Run EMMO Check - electrochemistry
      run: |
        if [ -f "electrochemistry.ttl" ]; then
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            electrochemistry.ttl
        else
          echo "electrochemistry.ttl not found!"
          exit 1
        fi

    - name: Run EMMO Check - electrochemistry-quantities
      run: |
        if [ -f "reference/electrochemistry-quantities.ttl" ]; then
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            reference/electrochemistry-quantities.ttl
        else
          echo "reference/electrochemistry-quantities.ttl not found!"
          exit 1
        fi

    - name: Run EMMO Check - electrochemistry-reference
      run: |
        if [ -f "reference/electrochemistry-reference.ttl" ]; then
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            reference/electrochemistry-reference.ttl
        else
          echo "reference/electrochemistry-reference.ttl not found!"
          exit 1
        fi

    - name: Run EMMO Check - electrochemistry-manufacturing
      run: |
        if [ -f "modules/electrochemistry-manufacturing.ttl" ]; then
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            modules/electrochemistry-manufacturing.ttl
        else
          echo "modules/electrochemistry-manufacturing.ttl not found!"
          exit 1
        fi

    - name: Run EMMO Check - electrochemistry-testing
      run: |
        if [ -f "modules/electrochemistry-testing.ttl" ]; then
          emmocheck --verbose --url-from-catalog \
            --skip test_namespace \
            --skip test_quantity_dimension \
            --configfile=.github/utils/emmocheck_config.yml \
            modules/electrochemistry-testing.ttl
        else
          echo "modules/electrochemistry-testing.ttl not found!"
          exit 1
        fi
