name: "Sphinx: Render docs"

on: 
  push:
    branches: [ sphinx ]
    
jobs:

  updatepages:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4 #Uses python install action from here: https://github.com/marketplace?type=actions
      with:
        python-version: '3.10'  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Markdown==3.4.3 rdflib==6.3.2  # Add any other dependencies if needed

    - name: Copy .ttl file to pages
      run: |
        cp ${GITHUB_WORKSPACE}/electrochemistry.ttl ${GITHUB_WORKSPACE}/docs/.

    - name: Render documentation from ttl
      run: python docs/scripts/ttl_to_html.py

    - name: Render documentation from md
      run: python docs/scripts/md_to_html.py

    - name: Commit updated documentation
      run: |
        cd ${GITHUB_WORKSPACE}
        git config --global user.email "${GIT_USER_EMAIL}"
        git config --global user.name "${GIT_USER_NAME}"
        git config pull.rebase false
        git add .
        git commit -m "Automatic update of github pages"
        git push origin master
        
  sphinx-build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "sphinx/"
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: sphinx/_build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/sphinx'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sphinx/_build/html

