name: "docs"

on: 
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'  # To ensure it runs on all PRs
    
env:
  GIT_USER_NAME: BattINFO Developers
  GIT_USER_EMAIL: "BattINFO@big-map.org"
    
jobs:

  updatepages:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4 #Uses python install action from here: https://github.com/marketplace?type=actions
      with:
        python-version: '3.10'  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Markdown==3.4.3 rdflib==6.3.2  pandoc # Add any other dependencies if needed
        
    - name: Render documentation from ttl
      run: python docs/scripts/ttl_to_rst.py

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y; apt-get install -y pandoc"

    - name: Create context file from ttl
      run: python docs/scripts/ttl_to_context.py

    - name: Check if HTML context directory exists
      run: |
        if [ ! -d "docs/_build/html/context/" ]; then
          echo "Creating HTML context directory"
          sudo mkdir -p docs/_build/html/context/
        else
          echo "HTML context directory already exists"
        fi

        if [ ! -d "docs/_build/html/assets/" ]; then
          echo "Creating HTML context directory"
          sudo mkdir -p docs/_build/html/assets/
        else
          echo "HTML assets directory already exists"
        fi

        if [ ! -d "docs/_build/html/versions/" ]; then
          echo "Creating HTML versions directory"
          sudo mkdir -p docs/_build/html/versions/
        else
          echo "HTML version directory already exists"
        fi

    - name: Copy assets directory to HTML directory
      run: sudo cp -r docs/assets/* docs/_build/html/assets/
    
    - name: Copy context file to HTML directory
      run: sudo cp context/context.json docs/_build/html/context/

    - name: Commit changes
      run: |
        git config --local user.email "${{ env.GIT_USER_EMAIL }}"
        git config --local user.name "${{ env.GIT_USER_NAME }}"
        git add context/context.json
        # Check for any changes to commit
        git diff --staged --quiet || git commit -m "Update context.json file"

    - name: Push changes
      run: git push origin HEAD:master

    - name: Fetch all tags and create version directories
      run: |
        git fetch --tags
        git tag | while read TAG; do
          sudo mkdir -p "docs/_build/html/versions/$TAG"

          # Apply foops recommendations and handle old/new file locations
          if [ -f "electrochemicalquantities.ttl" ]; then
            # For older versions
            python docs/scripts/apply_foops_recommendations.py electrochemicalquantities.ttl electrochemicalquantities-foops.ttl
            sudo cp "electrochemicalquantities-foops.ttl" "docs/_build/html/versions/$TAG/electrochemicalquantities.ttl"
          elif [ -f "modules/quantities.ttl" ]; then
            # For newer versions
            python docs/scripts/apply_foops_recommendations.py modules/quantities.ttl quantities-foops.ttl
            sudo cp "quantities-foops.ttl" "docs/_build/html/versions/$TAG/quantities.ttl"
          else
            echo "File not found!"
            exit 1
          fi
          
          python docs/scripts/apply_foops_recommendations.py electrochemistry.ttl electrochemistry-foops.ttl
          sudo cp "electrochemistry-foops.ttl" "docs/_build/html/versions/$TAG/electrochemistry.ttl"
          sudo cp "electrochemistry-inferred.ttl" "docs/_build/html/versions/$TAG/"

        if [ -d "context" ]; then
          echo "Context directory exists, copying context.json to $TAG"
          # Make sure the context directory exists in the version-specific directory
          sudo mkdir -p "docs/_build/html/versions/$TAG/context"
          # Copy context.json to the tag-specific context directory
          sudo cp "context/context.json" "docs/_build/html/versions/$TAG/context"
        else
          echo "No context directory found in the source directory."
        fi
        done

    - name: Copy TTL files to HTML directory
      run: |
        # Check if electrochemicalquantities.ttl is in the old or new location
        if [ -f "electrochemicalquantities.ttl" ]; then
          python docs/scripts/apply_foops_recommendations.py electrochemicalquantities.ttl electrochemicalquantities-foops.ttl
          sudo cp "electrochemicalquantities-foops.ttl" "docs/_build/html/electrochemicalquantities.ttl"
        elif [ -f "modules/quantities.ttl" ]; then
          python docs/scripts/apply_foops_recommendations.py modules/quantities.ttl quantities-foops.ttl
          sudo cp "quantities-foops.ttl" "docs/_build/html/quantities.ttl"
        else
          echo "Electrochemical quantities file not found!"
          exit 1
        fi
    
        # Apply foops recommendations to the electrochemistry file
        python docs/scripts/apply_foops_recommendations.py electrochemistry.ttl electrochemistry-foops.ttl
        sudo cp "electrochemistry-foops.ttl" "docs/_build/html/electrochemistry.ttl"
        sudo cp "electrochemistry-inferred.ttl" "docs/_build/html/electrochemistry-inferred.ttl"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentationHTML
        path: docs/_build/html/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html

      
