name: Validate Ontology Content

on: [pull_request]

jobs:
  emmocheck:
    name: EMMO Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        pip install -r requirements.txt

    - name: Load Ontology Configuration from YAML
      run: |
        python .github/scripts/ontology_toolkit.py >> $GITHUB_ENV

    - name: Run EMMO Check
      run: python .github/scripts/ontology_toolkit.py --run-emmocheck

    - name: Run OWL Reasoner Check
      run: python .github/scripts/ontology_toolkit.py --run-reasoner-check
      